"use client";
import{useEffect,useState}from"react";import{createClient}from"../../../../lib/supabase";import Link from"next/link";
export default function Admin({params}:{params:Promise<{slug:string}>}){
 const[slug,setSlug]=useState(""),[store,setStore]=useState<any>(),[products,setProducts]=useState<any[]>([]),[name,setName]=useState(""),[slogan,setSlogan]=useState(""),[newName,setNewName]=useState(""),[newPrice,setNewPrice]=useState(""),[newDesc,setNewDesc]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState("");
 async function load(sl:string){const s=createClient();const{data:u}=await s.auth.getUser();if(!u.user){location.href="/login";return}const{data:st}=await s.from("stores").select("*").eq("slug",sl).maybeSingle();if(!st){setLoading(false);return}const{data:m}=await s.from("store_users").select("role").eq("store_id",st.id).eq("user_id",u.user.id).maybeSingle();if(!m){location.href="/store/"+sl;return}const{data:p}=await s.from("products").select("id,name,description,price,status").eq("store_id",st.id).order("created_at",{ascending:false});setStore(st);setName(st.name);setSlogan(st.slogan||"");setProducts(p||[]);setLoading(false)}
 useEffect(()=>{params.then(({slug})=>{setSlug(slug);load(slug)})},[params]);
 async function saveStore(e:React.FormEvent){e.preventDefault();setSaving(true);setMsg("");const{error}=await createClient().from("stores").update({name:name.trim(),slogan:slogan.trim()}).eq("id",store.id);setMsg(error?error.message:"Boutique mise à jour.");setSaving(false);if(!error)setStore({...store,name,slogan})}
 async function addProduct(e:React.FormEvent){e.preventDefault();setMsg("");const price=Number(newPrice);if(!newName.trim()||!Number.isFinite(price)){setMsg("Nom et prix valides requis.");return}const{data,error}=await createClient().from("products").insert({store_id:store.id,name:newName.trim(),description:newDesc.trim(),price,status:"published"}).select("id,name,description,price,status").single();if(error){setMsg(error.message);return}setProducts([data,...products]);setNewName("");setNewPrice("");setNewDesc("");setMsg("Produit ajouté.")}
 async function delProduct(id:string){if(!confirm("Supprimer ce produit ?"))return;const{error}=await createClient().from("products").delete().eq("id",id).eq("store_id",store.id);if(error){setMsg(error.message);return}setProducts(products.filter(p=>p.id!==id));}
 if(loading)return <main className="container">Chargement...</main>;if(!store)return <main className="container"><h1>Boutique introuvable</h1></main>;
 return <main className="container"><nav className="nav" style={{margin:"-24px -24px 24px"}}><div className="brand">{store.name} <span>ADMIN</span></div><Link className="btn dark" href={"/store/"+slug}>Voir la boutique</Link></nav><h1>Tableau de bord</h1>{msg&&<p className="ok">{msg}</p>}<div className="grid"><div className="card"><h3>Produits</h3><div className="price">{products.length}</div></div><div className="card"><h3>Boutique</h3><div className="ok">{store.status}</div></div><div className="card"><h3>Slug</h3><div>{store.slug}</div></div></div><section className="card"><h2>Modifier la boutique</h2><form onSubmit={saveStore}><label>Nom</label><input className="input" value={name} onChange={e=>setName(e.target.value)} required/><label>Slogan</label><input className="input" value={slogan} onChange={e=>setSlogan(e.target.value)}/><button className="btn" disabled={saving}>{saving?"Enregistrement...":"Enregistrer"}</button></form></section><section className="card"><h2>Ajouter un produit</h2><form onSubmit={addProduct}><input className="input" placeholder="Nom du produit" value={newName} onChange={e=>setNewName(e.target.value)} required/><input className="input" type="number" min="0" step="0.01" placeholder="Prix" value={newPrice} onChange={e=>setNewPrice(e.target.value)} required/><textarea className="input" placeholder="Description" value={newDesc} onChange={e=>setNewDesc(e.target.value)}/><button className="btn green">Ajouter le produit</button></form></section><h2>Catalogue</h2><div className="card"><table className="table"><thead><tr><th>Produit</th><th>Prix</th><th>Statut</th><th></th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.price} {store.currency}</td><td>{p.status}</td><td><button className="btn dark" onClick={()=>delProduct(p.id)}>Supprimer</button></td></tr>)}</tbody></table></div></main>
}