"use client";
import {useState} from "react";
import {createClient} from "../../lib/supabase";
import {useRouter} from "next/navigation";
import Link from "next/link";

export default function Login(){
 const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [show,setShow]=useState(false);const [error,setError]=useState("");const [loading,setLoading]=useState(false);const router=useRouter();
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError("");const s=createClient();const {data,error}=await s.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error){setError(error.message);setLoading(false);return;}const {data:p}=await s.from("profiles").select("role").eq("id",data.user.id).single();if(p?.role==="super_admin"){router.push("/super-admin");return;}const {data:m}=await s.from("store_users").select("store_id,stores(slug)").eq("user_id",data.user.id).eq("role","owner").limit(1).maybeSingle();if(m?.stores){const st=Array.isArray(m.stores)?m.stores[0]:m.stores;router.push("/store/"+st.slug+"/admin");return;}router.push("/account");}
 return <main className="container" style={{maxWidth:520}}><div className="card"><h1>Connexion</h1><form onSubmit={submit}><label>Email</label><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><label>Mot de passe</label><div className="password-wrap"><input className="input" type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" className="eye-btn" onClick={()=>setShow(!show)} aria-label={show?"Masquer le mot de passe":"Afficher le mot de passe"}>{show?"Masquer":"Afficher"}</button></div>{error&&<p className="danger">{error}</p>}<button className="btn" disabled={loading}>{loading?"Connexion...":"Se connecter"}</button></form><p><Link href="/forgot-password" className="muted">Mot de passe oublié ?</Link></p><p>Pas encore de compte ? <Link href="/signup" className="muted">Créer une boutique</Link></p></div></main>
}